name: Mon Premier wf
env: 
 JOUR_DE_LA_SEMAINE: Lundi # Définition d'une variable d'environnement globale
on: [push]
jobs:
 say-greats:
  runs-on: ubuntu-latest
  steps:
  - name: Affiche le résultat hello world
    run: echo "Hello World !"
  - name: Print content pwd
    run: env
  - name: Etape 1
    run: echo "Ceci est l'étape 1"
    id: etape1
  - name: Affiche le résultat de l'étape 1
    run: echo " L'étape 1 a éxécuté le run ${{steps.etape1.conclusion }}"
  - name: Affiche le statut du job 
    run: echo "Nom du `job` ${{job.status}}"
  - name: Affiche l'OS du runner
    run: echo "Le runner utilise l'OS ${{ runner.os }}"
  - name: Utilise un secret
    run: echo "Le secret est ${{ secrets.MY_SECRET }}"
 test:
  # Système d'exploitation sur lequel le job s'exécute
  runs-on : ubuntu-latest
  # Stratégie de matrice
  strategy:
   # Utilisation d'une matrice pour exécuter des combinaisons de tests
   matrix:
    groupe_de_test: [1,2]
    node: [14,16]
  # Étapes du job
  steps:
    # Exécution des tests et sauvegarde des résultats dans un fichier texte
    # Le nom du fichier texte inclut l'indice du job dans la matrice
   - run: echo "Mock test logs" > test-job-${{ strategy.job-index }}.txt
   # Téléversement des logs
   - name: Téléversement des logs
     uses: actions/upload-artifact@v4
     with:
          # Nom unique pour l'artefact, incluant l'indice du job
        name: Build log for job ${{ strategy.job-index }}

          # Chemin du fichier à téléverser
        path: test-job-${{ strategy.job-index }}.txt
 
 job_de_salutation :  # Nom du job
    runs-on: ubuntu-latest  # Utilisation de la dernière version d'Ubuntu comme environnement de runner
    env :
      Salutation: Bonjour  # Définition d'une variable d'environnement au niveau du job
    steps :
      - name : "Dire bonjour à Pierre parce que c'est lundi"  # Nom de l'étape
        if : ${{ env.JOUR_DE_LA_SEMAINE == 'Lundi' }}  # Condition pour exécuter cette étape
        run : echo "$Salutation $Prenom. Aujourd'hui, c'est $JOUR_DE_LA_SEMAINE !"  # Commande à exécuter
        env :
          Prenom: Pierre  # Définition d'une variable d'environnement au niveau de l'étape


 print:
    runs-on: ubuntu-latest
    steps:
    - name: Affiche des infos github
      run: echo "Ce `workflow` a été déclenché par ${{ github.event_name }} sur la branche ${{ github.ref }}"

 build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Output node version
        run: node --version
        
# Nom du workflow Construction et déploiement
 build2:
    runs-on: ubuntu-latest
    # Sorties du job de construction
    outputs:
      build_id: ${{ steps.etape_construction.outputs.id_construction }}
    steps:
      - uses: actions/checkout@v4
      - name: Construction
        id: etape_construction
        run: |
          ./construire
          echo "::set-output name=id_construction::123"

 # Job de déploiement
 deploy:
    # Ce job nécessite le job de construction
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./deploiement --build ${{ needs.build.outputs.build_id }}

 # Job de débogage
 debug:
    # Ce job nécessite les jobs de construction et de déploiement
    needs: [build, deploy]
    runs-on: ubuntu-latest
    # Ce job s'exécute seulement si un autre job échoue
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v4
      - run: ./debugger
