name: Mon Premier wf
on: [push]
jobs:
 say-greats:
  runs-on: ubuntu-latest
  steps:
   - name: Print status, env, greats
   - run: echo "Hello World ! ${{ job.network }}, ${{ job.status }}"
   - run: env
 afficher:
    runs-on: ubuntu-latest
    steps:
    - name: Etape 1
      run: echo "Ceci est l'étape 1"
      id: etape1
    - name: Affiche des infos github
      run: echo "Ce `workflow` a été déclenché par ${{ github.event_name }} sur la branche ${{ github.ref }}"//fin
    
  
