name: Mon Premier wf
on: [push]
jobs:
 say-greats:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Hello World !"
   - run: env
   - run: echo "Ceci est l'étape 1"
   - run: echo "Nom du `job` ${{job.status}}"
   
    
  
